version: '3'
services:
   pg:
     image: postgres
     container_name: postgres
     ports:
       - 5432:5432
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=postgres
   web:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - pg
   kafka:
    image: wurstmeister/kafka
    ports:
      - 9092